config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, presence: true
  validates :body, presence: true

  validates_presence_of :name, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @posts = Post.new(post_params)
    if @posts.save
      redirect_to @posts, notice: 'Post created successfully'
    else
      redirect_to new_post_path, notice: 'There are some errors'
    end
  end

  def edit; end

  def update
    # @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: 'Post updated successfully'
    else
      redirect_to edit_post_path, notice: 'There are some errors'
    end
  end

  def destroy
    # @post = Post.find(params[:id])
    @post.delete
    redirect_to posts_url, notice: 'Post deleted successfully'
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appname</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post_form.html.erb
<%= form_for(@post) do |f|%>
  <p>
    <%= f.text_field :name%>
  </p>
  <p>
    <%= f.text_area :body %>
  </p>
  <%= f.submit%>
<% end %>
<%= link_to 'All posts', posts_path%>

app/views/posts/edit.html.erb
<h1>
  Edit posts
</h1>

<%= render 'posts/post_form'%>

app/views/posts/index.html.erb
<%= notice%>
<h1>
  index
</h1>
<%= link_to 'Create new post', new_post_path%>
<% @posts.each do |post| %>
  <p>
    <%= post.name %>
    <%= post.body %>
    <%= link_to "Show post", post_path(post)%>  
    <%= link_to "Update post", edit_post_path(post)%>
    <%= link_to "Delete", post, method: :delete, data:{ confirm: "Are you sure?"  } %>
  </p>
<%end%>

app/views/posts/new.html.erb
<h1>
  new posts
</h1>

<%= render 'posts/post_form'%>

app/views/posts/show.html.erb
<%= notice %>
<h1>
    <%= @post.name%>
</h1>

<p>
    <%= @post.body%>
</p>
<%= link_to 'edit', edit_post_path(@post) %>